### ISSUE TITLE
Angels don't move well on carpets

### ISSUE THREAD

**Issue by chaNcharge** [Suffril/Weeping-Angels#42]
When they go after you, they are unable to walk over carpets, they just move back and forth between carpet and non-carpet surfaces.

**Comment by SandedShoes** [comment]
https://media.giphy.com/media/11IPtUc4PUoyxq/giphy.gif

**Comment by SandedShoes** [comment]
![alt text](https://media.giphy.com/media/11IPtUc4PUoyxq/giphy.gif)

**Comment by Suffril** [comment]
@nictogen 

Shall we fall back to the Vanilla way of moving until we find a better solution or do you have a soultion in mind?

**Comment by chaNcharge** [comment]
I'd suggest doing the vanilla way of moving. I'm using f5 to cheat see the weeping angels move around, their moving pattern is very grid-like, kinda odd and irregular. The only downside of vanilla movement is that if an angel ends up in water, they'll probably end up swimming and you'll see them. I feel like that too can be solved if you have them sink like an iron when you look at them, and start floating when you look away.

**Comment by nictogen** [comment]
tbh imo they should be blocks but that's a whole thing

**Comment by Suffril** [comment]
Yeah, Sheriff explained that to me 

```Sheriff10/15/2018
It's the ideas me and Drake come up with for ATG before it ended
Fril10/15/2018
Ooo
Sheriff10/15/2018
Well weeping angels wouldn't really be mobs, they'd be blocks actually and they'd be found in villages and more built up structures, not everyone would be a weeping angel but those that were basically hunt/haunt you for X amount of time. When you get near an angel it will start to follow you around the world, doing the occasional spooky stuff and this is time it would almost taunt and play with the player before eventually killing them```
