### ISSUE TITLE
Crash when loading the server

### ISSUE THREAD

**Issue by Gamerbolts** [Suffril/Weeping-Angels#46]
Hi, I am creating a modpack and was testing things, the client loaded fine, but the server crashed while creating the world. Here is the crash log https://pastebin.com/ghMt2aQ8

Any help is appreciated. Thank you!

**Comment by Suffril** [comment]
Issue lays with the tardis mod, move this issue to there

**Comment by Gamerbolts** [comment]
ok posted on their github too, I saw both mods in the log and didn't know which to post to. Thank you
