### ISSUE TITLE
Weeping Angels can be seen through iron bars (and presumably glass panes), yet they don't freeze

### ISSUE THREAD

**Issue by MishaPlayer** [Suffril/Weeping-Angels#51]
I was on the modpack and found a weeping angel behind iron bars, but as it turns out, it didn't quantum lock.
They can also steal your key through the bars which makes sense... except for the fact that they can do it while you're looking at them.
You can also make them "dance" by strafing left and right, which is a bit funny but is still a bug.

**Comment by Suffril** [comment]
Thanks! I'll look into this!
